name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # (Opcional, mas seguro) Faz checkout do repo
      - uses: actions/checkout@v4

      # Gera a cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AlisonMaciel
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica no branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          # keep_history: true (padrão) — pode deixar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
